version: '3'
services:
  zeventquizz:
    image: zeventquizz
    build: .
    container_name: zeventquizz
    ports:
      - "5000:5000"
    depends_on:
      - mescouilles
  mescouilles:
    image: postgres:latest
    command: echo "listen_addresses = '*'" >> pg_hba.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zevent
      - POSTGRES_DB=zevent_quizz

