 jobs:
  build:
    executor: python/default
    docker:
      - image: circleci/python:3.10.7
        environment:
          ENV: CIRCLE
          DATABASE_URL: postgresql://circleci@localhost/circle_test
      - image: circleci/postgres:latest
        environment:
          PGHOST: localhost
          PGUSER: circleci
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Wait for db to run
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - python/save-cache
