"""empty message

Revision ID: 2de64263702b
Revises: 48436fb15808
Create Date: 2022-10-14 17:29:54.743945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de64263702b'
down_revision = '48436fb15808'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'quizz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quizz', 'battle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizz', 'battle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'quizz_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
