"""empty message

Revision ID: 48436fb15808
Revises: 1fcdd859d85a
Create Date: 2022-10-05 15:02:45.939961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48436fb15808'
down_revision = '1fcdd859d85a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battles', 'is_active')
    # ### end Alembic commands ###
