"""empty message

Revision ID: 54ff5f3742b0
Revises: 
Create Date: 2022-09-23 17:46:09.285444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ff5f3742b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'])
    op.add_column('battles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'battles', 'users', ['user_id'], ['id'])
    op.add_column('questions', sa.Column('quizz_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'questions', 'quizz', ['quizz_id'], ['id'])
    op.add_column('quizz', sa.Column('battle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quizz', 'battles', ['battle_id'], ['id'])
    op.add_column('teams', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('battle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'teams', 'battles', ['battle_id'], ['id'])
    op.drop_column('users', 'team')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'battle_id')
    op.drop_column('teams', 'user_id')
    op.drop_constraint(None, 'quizz', type_='foreignkey')
    op.drop_column('quizz', 'battle_id')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'quizz_id')
    op.drop_constraint(None, 'battles', type_='foreignkey')
    op.drop_column('battles', 'user_id')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'question_id')
    # ### end Alembic commands ###
